INSERT INTO MOVIE VALUES (1, 3, 4.5, '2020-08-15', 'Fast&Furious9');
INSERT INTO ACTOR VALUES (1, 'Dominic', 'Toreto', 8.0, 1);
INSERT INTO MOVIE_CAST VALUES (1,1);

SELECT * FROM MOVIE_CAST;
SELECT * FROM MOVIE;
SELECT * FROM ACTOR;