-- MySQL Script generated by MySQL Workbench
-- Tue Nov 30 10:33:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estudiantes_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `estudiantes_db` ;

-- -----------------------------------------------------
-- Schema estudiantes_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estudiantes_db` DEFAULT CHARACTER SET utf8 ;
USE `estudiantes_db` ;

-- -----------------------------------------------------
-- Table `estudiantes_db`.`LIBRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiantes_db`.`LIBRO` ;

CREATE TABLE IF NOT EXISTS `estudiantes_db`.`LIBRO` (
  `idLibro` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Editorial` VARCHAR(45) NULL,
  `Area` VARCHAR(45) NULL,
  PRIMARY KEY (`idLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudiantes_db`.`AUTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiantes_db`.`AUTOR` ;

CREATE TABLE IF NOT EXISTS `estudiantes_db`.`AUTOR` (
  `idAutor` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudiantes_db`.`ESTUDIANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiantes_db`.`ESTUDIANTE` ;

CREATE TABLE IF NOT EXISTS `estudiantes_db`.`ESTUDIANTE` (
  `idEstudiante` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Carrera` VARCHAR(45) NULL,
  `Edad` INT NULL,
  PRIMARY KEY (`idEstudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudiantes_db`.`LIBROAUTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiantes_db`.`LIBROAUTOR` ;

CREATE TABLE IF NOT EXISTS `estudiantes_db`.`LIBROAUTOR` (
  `LIBRO_idLibro` INT NOT NULL,
  `AUTOR_idAutor` INT NOT NULL,
  PRIMARY KEY (`LIBRO_idLibro`, `AUTOR_idAutor`),
  INDEX `fk_LIBRO_has_AUTOR_AUTOR1_idx` (`AUTOR_idAutor` ASC) VISIBLE,
  INDEX `fk_LIBRO_has_AUTOR_LIBRO_idx` (`LIBRO_idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_LIBRO_has_AUTOR_LIBRO`
    FOREIGN KEY (`LIBRO_idLibro`)
    REFERENCES `estudiantes_db`.`LIBRO` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIBRO_has_AUTOR_AUTOR1`
    FOREIGN KEY (`AUTOR_idAutor`)
    REFERENCES `estudiantes_db`.`AUTOR` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudiantes_db`.`PRESTAMO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiantes_db`.`PRESTAMO` ;

CREATE TABLE IF NOT EXISTS `estudiantes_db`.`PRESTAMO` (
  `LIBRO_idLibro` INT NOT NULL,
  `ESTUDIANTE_idEstudiante` INT NOT NULL,
  `FechaPrestamo` DATE NULL,
  `FechaDevolucion` DATE NULL,
  `Devuelto` TINYINT(1) NULL,
  PRIMARY KEY (`LIBRO_idLibro`, `ESTUDIANTE_idEstudiante`),
  INDEX `fk_LIBRO_has_ESTUDIANTE_ESTUDIANTE1_idx` (`ESTUDIANTE_idEstudiante` ASC) VISIBLE,
  INDEX `fk_LIBRO_has_ESTUDIANTE_LIBRO1_idx` (`LIBRO_idLibro` ASC) VISIBLE,
  CONSTRAINT `fk_LIBRO_has_ESTUDIANTE_LIBRO1`
    FOREIGN KEY (`LIBRO_idLibro`)
    REFERENCES `estudiantes_db`.`LIBRO` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIBRO_has_ESTUDIANTE_ESTUDIANTE1`
    FOREIGN KEY (`ESTUDIANTE_idEstudiante`)
    REFERENCES `estudiantes_db`.`ESTUDIANTE` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
