INSERT INTO MOVIE VALUES (1, 3, 4.5, '2019-01-10', 'Spiderverse');
INSERT INTO ACTOR VALUES (1, 'Carlos', 'Smith', 1.0, 1);
INSERT INTO MOVIE_CAST VALUES (1,1);

SELECT * FROM MOVIE_CAST;
SELECT * FROM MOVIE;
SELECT * FROM ACTOR;

INSERT INTO GENRES VALUES (1,true,'accion',3);
Select * From GENRES